"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import MyApp

# Implementing MyFrame1
class MyProject1MyFrame1( MyApp.MyFrame1 ):
	def __init__( self, parent ):
		MyApp.MyFrame1.__init__( self, parent )

	# Handlers for MyFrame1 events.
	def m_button1OnButtonClick( self, event ):
		# TODO: Implement m_button1OnButtonClick
		pass

	def m_slider2OnScroll( self, event ):
		# TODO: Implement m_slider2OnScroll
		pass

	def m_spinCtrl5OnTextEnter( self, event ):
		# TODO: Implement m_spinCtrl5OnTextEnter
		pass

	def m_slider4OnScroll( self, event ):
		# TODO: Implement m_slider4OnScroll
		pass

	def m_spinCtrl1OnTextEnter( self, event ):
		# TODO: Implement m_spinCtrl1OnTextEnter
		pass

	def m_spinCtrl2OnTextEnter( self, event ):
		# TODO: Implement m_spinCtrl2OnTextEnter
		pass

	def m_slider5OnScroll( self, event ):
		# TODO: Implement m_slider5OnScroll
		pass

	def m_spinCtrl3OnTextEnter( self, event ):
		# TODO: Implement m_spinCtrl3OnTextEnter
		pass

	def m_spinCtrlDouble1OnSpinCtrlText( self, event ):
		# TODO: Implement m_spinCtrlDouble1OnSpinCtrlText
		pass

	def m_checkBox1OnCheckBox( self, event ):
		# TODO: Implement m_checkBox1OnCheckBox
		pass

	def m_checkBox2OnCheckBox( self, event ):
		# TODO: Implement m_checkBox2OnCheckBox
		pass

	def m_button2OnButtonClick( self, event ):
		# TODO: Implement m_button2OnButtonClick
		pass

	def m_button3OnButtonClick( self, event ):
		# TODO: Implement m_button3OnButtonClick
		pass

	def m_grid1OnGridEditorCreated( self, event ):
		# TODO: Implement m_grid1OnGridEditorCreated
		pass

	def m_grid1OnGridSelectCell( self, event ):
		# TODO: Implement m_grid1OnGridSelectCell
		pass

	def m_spinCtrl4OnSpinCtrlText( self, event ):
		# TODO: Implement m_spinCtrl4OnSpinCtrlText
		pass

	def m_spinCtrl4OnTextEnter( self, event ):
		# TODO: Implement m_spinCtrl4OnTextEnter
		pass


